baseURL = "https://docs.paytrail.com/"
languageCode = "en-us"
title = "Paytrail Integration Guide"
theme = "dot"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
summaryLength = 140

[[menu.main]]
name = "Paytrail"
url = "https://paytrail.com"
weight = 1

[[menu.main]]
name = "Source"
url = "https://github.com/paytrail/documentation"
weight = 1

[params]
logo = "logo.png"

primary_color = "#e60094"
body_color = "#EEEEEE"
text_color = "#666666"
text_color_dark = "#323232"
white_color = "#ffffff"
light_color = "#f9f9f9"

font_family = "Lato"

[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/paytrail"

[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/paytrail"

[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/paytrail-oyj/"
