name: Docker Integration Test Suite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      TAG: "paytrail/documentation:latest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Build Docker Image
      run: docker build -t ${TAG} .
    - name: Run Container Tests
      env:
        # Create container with this name
        CONTAINER_NAME: hugo-nginx
        # Bind the running container to this port
        LOCAL_PORT: 8080
        # Wait <TIMEOUT> seconds before running tests to ensure the container is running.
        TIMEOUT: 5
      run: bash tests/docker.sh
